# Generated by Django 6.0.4 on 2026-04-24 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_update_user_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='teammember',
            name='unique_user_team_membership',
        ),
        migrations.AddField(
            model_name='team',
            name='max_members',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='is_kaptain',
            field=models.BooleanField(default=False, help_text='User can create and manage a team.'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.team'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.user'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('user', 'team'), name='uniq_user_team'),
        ),
    ]
