# Generated by Django 6.0.4 on 2026-04-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_kaptain',
            field=models.BooleanField(default=False, help_text='Auto-synced with role=CAPTAIN'),
        ),
    ]
