# Generated by Django 6.0.4 on 2026-04-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_alter_user_is_kaptain'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
