# Generated by Django 6.0 - schedule subscriptions, can_create_hackathons

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathon", "0005_hackathon_variant_a_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_create_hackathons",
            field=models.BooleanField(
                default=False,
                help_text="Может создавать хакатоны (выбор при регистрации или назначение в админке).",
            ),
        ),
        migrations.CreateModel(
            name="HackathonScheduleSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hackathon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_subscriptions",
                        to="hackathon.hackathon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_subscriptions",
                        to="hackathon.user",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="ScheduleNotificationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dedupe_key", models.CharField(db_index=True, max_length=128)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hackathon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_notification_logs",
                        to="hackathon.hackathon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_notification_logs",
                        to="hackathon.user",
                    ),
                ),
            ],
            options={
                "ordering": ("-sent_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="hackathonschedulesubscription",
            constraint=models.UniqueConstraint(
                fields=("user", "hackathon"), name="uniq_user_hackathon_schedule_subscription"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulenotificationlog",
            constraint=models.UniqueConstraint(
                fields=("user", "dedupe_key"), name="uniq_schedule_notify_dedupe"
            ),
        ),
    ]
