# Generated by Django 6.0.4 on 2026-04-29 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_teammember_telegram_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_hackathons',
            field=models.BooleanField(default=False, help_text='Может создавать хакатоны (выбор при регистрации или назначение в админке).'),
        ),
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('schedule_sheet_url', models.URLField(blank=True, help_text='Ссылка на Google Таблицу с расписанием (опционально).', max_length=500)),
                ('is_team_join_open', models.BooleanField(default=True, help_text='Капитаны могут подключать команды к этому хакатону.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hackathons', to='hackathon.user')),
                ('organizers', models.ManyToManyField(blank=True, help_text='Права организатора через связь many-to-many.', related_name='organized_hackathons', to='hackathon.user')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HackathonScheduleSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_subscriptions', to='hackathon.hackathon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_subscriptions', to='hackathon.user')),
            ],
            options={
                'ordering': ('-updated_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'hackathon'), name='uniq_user_hackathon_schedule_subscription')],
            },
        ),
        migrations.CreateModel(
            name='HackathonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_teams', to='hackathon.hackathon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_links', to='hackathon.team')),
            ],
            options={
                'ordering': ('-joined_at',),
                'constraints': [models.UniqueConstraint(fields=('hackathon', 'team'), name='uniq_hackathon_team')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedupe_key', models.CharField(db_index=True, max_length=128)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_notification_logs', to='hackathon.hackathon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_notification_logs', to='hackathon.user')),
            ],
            options={
                'ordering': ('-sent_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'dedupe_key'), name='uniq_schedule_notify_dedupe')],
            },
        ),
    ]
